### ISSUE TITLE
Assignments 总分在卡片上显示错误

### ISSUE THREAD

**Issue by macromogic** [ArchOJ/feedback#1]
## Bug 描述

Assignment 提交AC后在卡片上没有正确显示当前分数。

## 复现步骤

1. 进入任一开放的Assignment（如当前的Assignment 1）；
2. 提交任一代码并获得AC；
3. 返回卡片页面，分数依然显示0。

## 发生时间

2020年10月12日-13日

## 预期行为

卡片右上角显示当前作业得分（非0）。

## 截图

暂无，暂未获得账号。

**Comment by ziqin** [comment]
已定位问题。由重构时错误地调整了代码行顺序导致。
