### ISSUE TITLE
SA账号无法查看submission detail

### ISSUE THREAD

**Issue by CharlotteE67** [ArchOJ/feedback#2]
## Bug Description | Bug 描述

使用SA账号登陆时，在submission页面查看学生提交的detail会显示403 no access。

## Additional context | 补充情况

新建的账号似乎存在这个问题，有其他SA反馈自己可以正常查看

**Comment by ziqin** [comment]
Confirmed.

**Comment by ziqin** [comment]
再看看？

已修改相应配置。

**Comment by CharlotteE67** [comment]
OK了，感谢！
