### ISSUE TITLE
是否需要把 Token 临时记录在 Cookie 里实现自动登录

### ISSUE THREAD

**Issue by Gogomoe** [ArchOJ/feedback#3]
现在是只把 Token 存在 Vue 里吧，导致每次刷新页面、打开url的时候都需要重新登录。

我觉得临时把 Token 放进 Cookie 里，实现自动登录可能用户体验会好一点

顺便提交一个疑似bug，在 `/submission` 刷新页面后，回到登录页面带了一个 redirect 的 query string `/user/login?redirect=/submission` ，但登陆上后仍然是转跳到 `/course`

**Comment by jerrylususu** [comment]
多谢反馈！后者是一个独立的跳转失效 bug，我们会另外开一个 issue 处理。前者我们会进行讨论，现在刷新需要重新登陆的确是一个比较恼人的 User Experience 问题。

**Comment by ziqin** [comment]
Arch OJ 采用 token-based authentication，不使用 Cookie。

正常情况下，若勾选“Remember me”，Arch OJ 前端会将 token 存储在浏览器的 [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) 中。下次需要登录前，会先检查 localStorage 中是否已有 token。若有，则直接使用。

**Comment by ziqin** [comment]
最近出现的自动登录失效问题由近期的一个变更 https://github.com/ArchOJ/archoj-frontend/commit/2fdbd7f6c95f4b51f4bf9b5fabc772d7d82c4024 引入。该变更将 “Remember me” 显示为默认勾选。然而，由于这不是用户的主动操作，对应的表单项的值实际上为 `undefined`。这导致默认勾选的 “Remember me” 实际上没有生效。而如果用户主动取消勾选并再次勾选，则可以生效。

此问题可通过添加对 `undefined` 的判断修复。
